hl.on("hyprland.start", function()
	hl.exec_cmd("xset r rate 190 50")
	hl.exec_cmd("hyprctl setcursor $cursor_theme $cursor_size")
	hl.exec_cmd("systemctl --user start --no-block thunar.service")
	hl.exec_cmd("hyprsunset")
	hl.exec_cmd("hypridle")
	hl.exec_cmd("hyprlogd snitch")
	hl.exec_cmd("timeline-hyprfocusd-snitch")
	-- hl.exec_cmd("alga power on")
	hl.exec_cmd("~/.home-manager/scripts/battery-monitor.sh")
	hl.exec_cmd("kdeconnectd")
	hl.exec_cmd("qs -d -n")
	-- hl.exec_cmd("~/.config/hypr/scripts/open_chromium.sh")
	hl.exec_cmd("handy --start-hidden")
end)
