### AUTOSTART ###

env = PATH,$HOME/.cargo/bin:$PATH

exec-once = xset r rate 190 50
exec-once = waybar & hyprpaper
exec-once = hyprctl setcursor $cursor_theme $cursor_size
exec-once = easyeffects --gapplication-service
exec-once = hyprsunset
exec-once = hypridle
exec-once = hyprfocusd
exec-once = alga power on
