### AUTOSTART ###

env = PATH,$HOME/.cargo/bin:$PATH

exec-once = xset r rate 500 20
exec-once = hyprpaper
exec-once = hyprctl setcursor $cursor_theme $cursor_size
exec-once = hypridle
exec-once = hyprlogd
exec-once = ~/.home-manager/config_files/swww/gif_wallpaper_cycle.sh
exec-once = ~/.config/hypr/scripts/which-key.sh -b
exec-once = ~/.home-manager/config_files/hypr/scripts/open_chromium.sh
