# this
class_aliases {
    "chromium-browser" = "chromium"
    "plasticx" = "plastic"
    "gcr-prompter" = "keyring"
    ".blueman-manager-wrapped" = "blueman"
    "com.github.wwmm.easyeffects" = "easyeffects"
    "org.gnome.Nautilus" = "nautilus"
    "org.pwmt.zathura" = "zathura"
    "chrome-chat.openai.com__-Default" = "ChatGPT"
    "chrome-outlook.live.com__mail_0_-Default" = "outlook"
    "chrome-discord.com__channels_@me-Default" = "discord"
    "chrome-calendar.google.com__-Default" = "calendar"
    "chrome-web.whatsapp.com__-Default" = "whatsapp"
}
# or this
class_alias = "chromium-browser", "chromium"
class_alias = "plasticx", "plastic"
class_alias = "gcr-prompter", "keyring"
class_alias = ".blueman-manager-wrapped", "blueman"
class_alias = "com.github.wwmm.easyeffects", "easyeffects"
class_alias = "org.gnome.Nautilus", "nautilus"
class_alias = "org.pwmt.zathura", "zathura"
class_alias = "chrome-chat.openai.com__-Default", "ChatGPT"
class_alias = "chrome-outlook.live.com__mail_0_-Default", "outlook"
class_alias = "chrome-discord.com__channels_@me-Default", "discord"
class_alias = "chrome-calendar.google.com__-Default", "calendar"
class_alias = "chrome-web.whatsapp.com__-Default", "whatsapp"
