return {
    class_aliases = {
        { "chromium-browser", "chromium" },
        { "Chromium-browser", "chromium" },
        { "plasticx", "plastic" },
        { "gcr-prompter", "keyring" },
        { ".blueman-manager-wrapped", "blueman" },
        { "com.github.wwmm.easyeffects", "easyeffects" },
        { "org.gnome.Nautilus", "nautilus" },
        { "org.pwmt.zathura", "zathura" },
        { "com.network.manager", "nmgui" },
        { ".virt-manager-wrapped", "Virtual Machine Manager" },
        { "com.obsproject.Studio", "obs" },
        { "org.pulseaudio.pavucontrol", "Volume Control" },
        { "chrome-chat.openai.com__-Default", "ChatGPT" },
        { "chrome-outlook.live.com__mail_0_-Default", "outlook" },
        { "chrome-discord.com__channels_@me-Default", "discord" },
        { "chrome-calendar.google.com__-Default", "calendar" },
        { "chrome-web.whatsapp.com__-Default", "whatsapp" },
        { "chrome-play.qobuz.com__user_library_favorites_tracks-Default", "qobuz" },
        { "chrome-app.slack.com__client-Default", "slack" },
        { "chrome-app.todoist.com__app_upcoming-Default", "todoist" },
        { "chrome-excel.cloud.microsoft__open_onedrive_-Default", "excel" },
        { "chrome-onedrive.live.com__-Default", "onedrive" },
        { "chrome-t470__8123_-Default", "home assistant" },
    },
}
