monitorv2 {
 output = HDMI-A-1
 mode = 3840x2160@144.00
 scale = 1.0
 transform = 0
 position = 0x0

 supports_wide_color = 1
 supports_hdr = 1
 bitdepth = 10
 cm = hdr
 sdrbrightness = 1.4
 sdr_min_luminance = 0.0

}


general {
    gaps_out =  200, 746.666, 200, 746.666
}

bindd = SUPER, F12, Toggle Outer Gaps, exec, sh -c 'f="${XDG_RUNTIME_DIR:-/tmp}/hypr-gaps-out-off"; if [ -e "$f" ]; then hyprctl keyword general:gaps_out 200,746.666,200,746.666 && rm -f "$f"; else hyprctl keyword general:gaps_out 0,0,0,0 && touch "$f"; fi'

decoration {
    dim_special = 0.0
}
