### VARIABLES ###

$SUPER = SUPER
$terminal = kitty
$browser = chromium
$desktopLauncher = ~/.home-manager/scripts/launch-desktop-entry.sh
$email = $desktopLauncher webapp-outlook
$music = $desktopLauncher webapp-qobuz
$onedrive = $desktopLauncher webapp-onedrive
$unity = /home/gusjengis/Unity/Hub/Editor/6000.0.23f1/Editor/Unity /home/gusjengis/Cloud Repositories/3DT/
$gpt = $desktopLauncher webapp-chatgpt
$fileManager = thunar 
$whatsapp = $desktopLauncher webapp-whatsapp
$excel = $desktopLauncher webapp-excel
$calendar = $desktopLauncher webapp-calendar
$todos = $desktopLauncher webapp-todoist
$homeAssistant = $desktopLauncher webapp-home-assistant

# trying to hide window decorations, doesn't seem to work
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = GTK_CSD=0
