### VARIABLES ###

$SUPER = SUPER
$webapp = $browser --app # for chromium
$terminal = kitty
$browser = chromium
$email = $webapp=https://mail.google.com/mail/u/0/#inbox
$photos = $webapp=https://www.icloud.com/photos/
$music = $webapp=https://music.youtube.com/
$gpt = $webapp=https://chat.openai.com 
$fileManager = thunar 
$whatsapp = $webapp=https://web.whatsapp.com/
$excel = $webapp=https://excel.cloud.microsoft/open/onedrive/?docId=6C5E5C1090A0D9FE%21533129&driveId=6C5E5C1090A0D9FE
$calendar = $webapp=https://calendar.google.com/
$typing = $webapp=https://monkeytype.com/

