### VARIABLES ###

$SUPER = SUPER
$webapp = $browser --app # for chromium
$terminal = kitty
$browser = chromium
$email = $webapp=https://outlook.live.com/mail/0/ 
$discord = $webapp=https://discord.com/channels/@me 
$music = $webapp=https://play.qobuz.com/user/library/favorites/tracks 
$slack = $webapp=https://app.slack.com/client
$onenote = chromium --new-window 'https://onedrive.live.com/edit.aspx?resid=F914021332F5F730!s26901b37eb6341209ca223aa78a7d896&migratedtospo=true&wd=target%28Market%20Research.one%7C4939292d-a3e9-4dcb-b793-d5b2d4bf5782%2FPotential%20Markets%7C2e020fe7-4e97-4361-932a-cfc7adf8d34c%2F%29&wdorigin=NavigationUrl'
$solidworks = chromium --new-window 'https://my.3dexperience.3ds.com/cnb/my-account/subscriptions'
$unity = /home/gusjengis/Unity/Hub/Editor/6000.0.23f1/Editor/Unity /home/gusjengis/Cloud Repositories/3DT/
$gpt = $webapp=https://chat.openai.com 
$rocket_money = $webapp=https://app.rocketmoney.com/
$fileManager = thunar 
$menu = wofi --show drun
$whatsapp = $webapp=https://web.whatsapp.com/
