### VARIABLES ###

$SUPER = SUPER
$webapp = $browser --app # for chromium
$terminal = kitty
$browser = chromium
$email = $webapp=https://outlook.live.com/mail/0/ 
$discord = $webapp=https://discord.com/channels/@me 
$music = $webapp=https://play.qobuz.com/user/library/favorites/tracks 
$slack = $webapp=https://app.slack.com/client
$onedrive = chromium --new-window 'https://onedrive.live.com/?view=1'
$solidworks = chromium --new-window 'https://my.3dexperience.3ds.com/cnb/my-account/subscriptions'
$unity = /home/gusjengis/Unity/Hub/Editor/6000.0.23f1/Editor/Unity /home/gusjengis/Cloud Repositories/3DT/
$gpt = $webapp=https://chat.openai.com 
$rocket_money = $webapp=https://app.rocketmoney.com/
$fileManager = thunar 
$whatsapp = $webapp=https://web.whatsapp.com/
$excel = $webapp=https://excel.cloud.microsoft/open/onedrive/?docId=6C5E5C1090A0D9FE%21533129&driveId=6C5E5C1090A0D9FE
$calendar = $webapp=https://calendar.google.com/
