source = $HOME/.config/hypr/variables.conf

### TERMINAL
bindd = SUPER CTRL ALT SHIFT, T, Hidden, togglespecialworkspace, terminal 
workspace = special:terminal, on-created-empty:$terminal

### BLUETOOTH
bindd = SUPER SHIFT, B, Bluetooth, togglespecialworkspace, bluetooth 
workspace = special:bluetooth, on-created-empty:blueman-manager

### CALENDAR
bindd = SUPER, C, Calendar, togglespecialworkspace, calendar 
workspace = special:calendar, on-created-empty:$calendar

### Email
bindd = SUPER, E, Email, togglespecialworkspace, email 
workspace = special:email, on-created-empty:$email  

### FILES
bindd = SUPER, F, Files, togglespecialworkspace, files 
workspace = special:files, on-created-empty:$fileManager

### GPT
bindd = SUPER, G, ChatGPT, togglespecialworkspace, gpt 
workspace = special:gpt, on-created-empty:$gpt

### INTERNET
bindd = SUPER, I, Internet, togglespecialworkspace, browser 
workspace = special:browser, on-created-empty:$browser 

### MUSIC
bindd = SUPER, M, Music, togglespecialworkspace, music 
workspace = special:music, on-created-empty:$music

### NOTES
bindd = SUPER, N, Notes, togglespecialworkspace, notes  
workspace = special:notes , on-created-empty:obsidian

### WHATSAPP
bindd = SUPER, W, Whatsapp, togglespecialworkspace, whatsapp 
workspace = special:whatsapp, on-created-empty:$whatsapp

### WIFI
bindd = SUPER SHIFT, W, Wi-Fi, togglespecialworkspace, wifi 
workspace = special:wifi, on-created-empty:nmgui

### ZOOM
bindd = SUPER, Z, Zoom, togglespecialworkspace, zoom 
workspace = special:zoom, on-created-empty:zoom
