source = $HOME/.config/hypr/variables.conf

### TERMINAL
bindd = SUPER CTRL ALT SHIFT, T, Hidden, togglespecialworkspace, terminal 
workspace = special:terminal, on-created-empty:$terminal

### BLUETOOTH
bindd = SUPER SHIFT, B, Bluetooth, togglespecialworkspace, bluetooth 
workspace = special:bluetooth, on-created-empty:blueman-manager

### CALENDAR
bindd = SUPER, C, Calendar, togglespecialworkspace, calendar 
workspace = special:calendar, on-created-empty:$calendar

### Email
bindd = SUPER, E, Email, togglespecialworkspace, email 
workspace = special:email, on-created-empty:$email  

### FILES
bindd = SUPER, F, Files, togglespecialworkspace, files 
workspace = special:files, on-created-empty:$fileManager

### GPT
bindd = SUPER, G, ChatGPT, togglespecialworkspace, gpt 
workspace = special:gpt, on-created-empty:$gpt

### INTERNET
bindd = SUPER, I, Internet, togglespecialworkspace, browser 
workspace = special:browser, on-created-empty:$browser 
windowrulev2 = workspace special:browser, ^(.*chromium-browser.*)$

### MUSIC
bindd = SUPER, M, Music, togglespecialworkspace, music 
workspace = special:music, on-created-empty:$music

### NOTES
bindd = SUPER, N, Notes, togglespecialworkspace, notes  
workspace = special:notes , on-created-empty:$notes

### WHATSAPP
bindd = SUPER, W, Whatsapp, togglespecialworkspace, whatsapp 
workspace = special:whatsapp, on-created-empty:$whatsapp

### WIFI
bindd = SUPER SHIFT, W, Wi-Fi, togglespecialworkspace, wifi 
workspace = special:wifi, on-created-empty:nmgui

### ZOOM
bindd = SUPER, Z, Zoom, togglespecialworkspace, zoom 
workspace = special:zoom, on-created-empty:$zoom

### SNOWED INN
bindd = SUPER, S, Snowed Inn, togglespecialworkspace, snowed 
workspace = special:snowed, on-created-empty:$snowed_inn

### DRAGONFLY LANE 
bindd = SUPER, D, Dragonfly Lane, togglespecialworkspace, dragonfly 
workspace = special:dragonfly, on-created-empty:$dragonfly_lane

### RIGHT UNDER OUR NOSES
bindd = SUPER, R, Right Under Our Noses, togglespecialworkspace, right 
workspace = special:right, on-created-empty:$right

### TYPING
bindd = SUPER, T, Monkeytype, togglespecialworkspace, typing 
workspace = special:typing, on-created-empty:$typing

### PHOTOS
bindd = SUPER, P, Photos, togglespecialworkspace, photos  
workspace = special:photos , on-created-empty:$photos
