source = $HOME/.config/hypr/variables.conf

### TERMINAL
bindd = SUPER CTRL ALT SHIFT, T, Hidden, togglespecialworkspace, terminal 
workspace = special:terminal, on-created-empty:$terminal

### CALENDAR
bindd = SUPER, C, Calendar, togglespecialworkspace, calendar 
workspace = special:calendar, on-created-empty:$calendar

### Email
bindd = SUPER, E, Gmail, togglespecialworkspace, email 
workspace = special:email, on-created-empty:$email  

### FILES
bindd = SUPER, F, Files, togglespecialworkspace, files 
workspace = special:files, on-created-empty:$fileManager

### GPT
bindd = SUPER, G, ChatGPT, togglespecialworkspace, gpt 
workspace = special:gpt, on-created-empty:$gpt

### INTERNET
bindd = SUPER, I, Internet, togglespecialworkspace, browser 
workspace = special:browser, on-created-empty:$browser 
windowrulev2 = workspace special:browser, ^(.*chromium-browser.*)$

### MUSIC
bindd = SUPER, M, Music, togglespecialworkspace, music 
workspace = special:music, on-created-empty:$music

### TYPING
bindd = SUPER, T, Monkeytype, togglespecialworkspace, typing 
workspace = special:typing, on-created-empty:$typing
